### PR TITLE
Update Copypasta.java

### PR DESCRIPTION
**Pull request by Fireflies**
Can you smell my disapproval?

### CODE REVIEW

**Comment by SpongyBacon** [comment]
r00d

**Comment by Fireflies** [comment]
You didn't even pull? :sob:

**Comment by SpongyBacon** [comment]
y new instance of random each time?

**Comment by SpongyBacon** [comment]
y no amazing api?

**Comment by Fireflies** [comment]
Busy working on an amazing API, [Fireflies/jslack](https://github.com/Fireflies/jslack) :smirk_cat:

**Comment by SpongyBacon** [comment]
404 :'(

**Comment by Fireflies** [comment]
Private repo for now, will publish when somewhat stable :stuck_out_tongue:

**Comment by SpongyBacon** [comment]
kewl :3

**Pull request closed without merging**
